Bump ZarrReader to 0.5.2 and omero-server to 5.6.12
IDR/deployment pull request #429
Opened 2024-07-30 10:16 UTC by dominikl

See title.

2024-08-02 12:42 UTC, dgault approved these changes

2024-08-12 16:16 UTC, sbesson approved these changes
Deployment changes look good to me. From this morning's IDR meeting, I understand the goal is to have this deployed onto idr-testing alongside the image-region micro-service with the same version of ZarrReader for a new round of testing.

At the code level, this raises the question of whether the micro-service addition will come as a separate PR and be included here. Note that from an deployment perspective, it should be also possible to update `prod122` with these changes first and schedule the integration of the micro-service at a later date.

2024-08-14 09:03 UTC, dgault requested changes

2024-08-15 08:06 UTC, merged

2024-08-15 09:46 UTC, sbesson commented
The following playbooks `idr-omero.yml`, `idr-omero-readonly.yml` and `idr-omero-web.yml` have been successfully executed against `prod122` upgrading the server and web environments as required.

Note that as part of this action, the PostgreSQL configuration file was "downgraded" to the state installed by the `ome.postgresql:5.4.0` role. @khaledk2 manually added `effective_cache_size = 24GB` to the configuration file which was the primarily change from the CentOS 7 -> Rocky Linux 9 upgraded. Mid-term, this should be addressed properly by completing the work on #424.